from __future__ import annotations

from dataclasses import dataclass

from src.models._validation import validate_positive_int, validate_symbol


VALID_TARGETS = frozenset({"here", "out", "in_2", "in_3"})


@dataclass(frozen=True)
class ProducedObject:
    """Object generated by a rule and its communication target."""

    symbol: str
    count: int = 1
    target: str = "here"

    def __post_init__(self) -> None:
        validate_symbol(self.symbol)
        validate_positive_int(self.count, "count")
        if self.target not in VALID_TARGETS:
            raise ValueError(
                f"target must be one of {sorted(VALID_TARGETS)}, got {self.target!r}"
            )

    @property
    def is_local(self) -> bool:
        return self.target == "here"

    @property
    def is_out(self) -> bool:
        return self.target == "out"

    @property
    def target_membrane_id(self) -> int | None:
        if not self.target.startswith("in_"):
            return None
        return int(self.target.removeprefix("in_"))

